### ISSUE TITLE
not able to see the cross symbol on the selected items in screen.

### ISSUE THREAD

**Issue by Santanubhar** [CuppaLabs/angular2-dataGrid#10]

**Comment by CuppaLabs** [comment]
Could you please provide the screenshot ?

**Comment by Santanubhar** [comment]
This issue is resolved. attached the front awesome link externally to fix this issue.
Another issue i am facing now that is in Internet explorer the deleting functionality from the field by clicking on the cross icon is not working. In chrome and safari it is working but in internet explorer this functionality is not working.
