### ISSUE TITLE
Row click listeners

### ISSUE THREAD

**Issue by PsyGik** [CuppaLabs/angular2-dataGrid#2]
Reading through the code, I couldn't find any api supporting row click listeners. Is this feature wip? PRs accepted?

**Comment by CuppaLabs** [comment]
Yes, it is work in progress. Working on custom template for row and column. Handling as part of this feature. It should be available end of this week..

**Comment by CuppaLabs** [comment]
Hi, Implemented row click event. The new event would return the row object.
