### ISSUE TITLE
cuppa-ng2-grid/cuppa-ng2-dataGrid 404 (Not Found)

### ISSUE THREAD

**Issue by saineshwar** [CuppaLabs/angular2-dataGrid#5]
![image](https://cloud.githubusercontent.com/assets/8281689/26121672/ab6c91f0-3a92-11e7-9671-473db8a66234.png)

**Comment by CuppaLabs** [comment]
Did you install datagrid package and imported into your project ?  Are you trying to use the package or run the project in local. Please provide the issue in detail. The package and project are working fine. Hence closing the issue.

**Comment by saineshwar** [comment]
1) I have installed packages here is screen shot of it
![image](https://cloud.githubusercontent.com/assets/8281689/26137472/f6d96fee-3adf-11e7-9f4d-43eceef586b3.png)
2) Import CuppaDataGridModule in appmodule
![image](https://cloud.githubusercontent.com/assets/8281689/26137566/a546b352-3ae0-11e7-9e8c-f883fc2769fc.png)
3) the CuppaDemoGridComponent where i am passing data to view
![image](https://cloud.githubusercontent.com/assets/8281689/26137585/c6868330-3ae0-11e7-86f0-37f68e259add.png)
4) Grid on View
![image](https://cloud.githubusercontent.com/assets/8281689/26137615/f1ab54a0-3ae0-11e7-9e33-f1d1b843e245.png)
5) one question it do not have any setting in systemjs.config.js
