### ISSUE TITLE
cuppa-ng2-grid/cuppa-ng2-dataGrid 404 (Not Found) 

### ISSUE THREAD

**Issue by saineshwar** [CuppaLabs/angular2-dataGrid#6]
1) I have installed packages here is screen shot of it
![image](https://cloud.githubusercontent.com/assets/8281689/26137472/f6d96fee-3adf-11e7-9f4d-43eceef586b3.png)
2) Import CuppaDataGridModule in appmodule
![image](https://cloud.githubusercontent.com/assets/8281689/26137566/a546b352-3ae0-11e7-9e8c-f883fc2769fc.png)
3) the CuppaDemoGridComponent where i am passing data to view
![image](https://cloud.githubusercontent.com/assets/8281689/26137585/c6868330-3ae0-11e7-86f0-37f68e259add.png)
4) Grid on View
![image](https://cloud.githubusercontent.com/assets/8281689/26137615/f1ab54a0-3ae0-11e7-9e33-f1d1b843e245.png)
5) one question it do not have any setting in systemjs.config.js

**Comment by CuppaLabs** [comment]
Could you please let me know if you are using angular-cli to scaffold your application ? no configuration is required in systemjs.config.js. Also did you declare the imported module, like below,
@NgModule({
  bootstrap: [ AppComponent ],
  declarations: [
    AppComponent,
    NoContentComponent  ],
  imports: [
    BrowserModule, 
    FormsModule,
    HttpModule,
    CuppaDataGridModule // Import DataGrid module variable here
  ]
})

**Comment by saineshwar** [comment]
Not using angular-cli
