### ISSUE TITLE
You may need an appropriate loader to handle this file type/.angular2-multiselect-dropdown/multiselect.component.scss

### ISSUE THREAD

**Issue by Bikeshs** [CuppaLabs/angular2-dataGrid#7]
I am using webpack with angular2 and want use multiselect dropdown ,i have followed all steps but getting error on each time.please do needful.I have tried lot of times using loader but not done.
{
                    test: /\.sass$/,
                    // Passing indentedSyntax query param to node-sass
                    loaders: ["style", "css", "sass?indentedSyntax"]
                },
not working.

**Comment by CuppaLabs** [comment]
Hi,
I am using angular-cli to build apps.

**Comment by CuppaLabs** [comment]
Issue raised in wrong repository. Please raise it in appropriate repository.
