### ISSUE TITLE
EXCEPTION: Uncaught (in promise): Error: Error in ./AngularMultiSelect class AngularMultiSelect - inline template:3:18 caused by: Cannot read property 'length' of undefined TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Bikeshs** [CuppaLabs/angular2-dataGrid#8]
![image](https://cloud.githubusercontent.com/assets/24294996/26589693/4265a306-4576-11e7-9790-5f3ebaf1c76e.png)

I have followed all steps but its not working properly .I am using webpack.
Please check and resolve asap.

**Comment by CuppaLabs** [comment]
This is not the correct repository for this issue. Hence, closing it. Open it in the appropriate repository.
